### ISSUE TITLE
lie.polyfill.js/lie.polyfill.min.js missing in dist/

### ISSUE THREAD

**Issue by clmath** [calvinmetcalf/lie#15]
The README.md is mentioning a polyfill build that is not present in the dist directory.

Has it been forgotten in the last build or should the README.md be updated ?

**Comment by calvinmetcalf** [comment]
hm woops

**Comment by calvinmetcalf** [comment]
fixed

**Comment by clmath** [comment]
Thank you for your very quick fix !
