### ISSUE TITLE
Idiomatic way to use this inside a promise function

### ISSUE THREAD

**Issue by Valve** [calvinmetcalf/lie#17]
Hi, Great library!

What are the options of using `this` inside a promise function?

```javascript
return new Promise(function(resolve, reject){
  // I want to access this here, but it's a global object, not current object
});
```
I can use good old **`that`**:

```javascript
var that = this;
return new Promise(function(resolve, reject){
  that.callMethod();
});
```

I also could use **[bind](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind)**.

```javascript
return new Promise(function(resolve, reject){
  this.callMethod();
}.bind(this));
```

Which is my preferred way, but I'm afraid it could break **lie** in unexpected ways.

Please let me know of a preferred way of using **`this`**.

Thanks

**Comment by calvinmetcalf** [comment]
Either of those would work perfectly though bind is sometimes slower so I
tend towards the other

**Comment by Valve** [comment]
Thanks!
