### ISSUE TITLE
Unhandled rejection detection

### ISSUE THREAD

**Issue by benjamingr** [calvinmetcalf/lie#20]
If you'd like, implementing this API would be really awesome, Bluebird When and native promises on the server do this:

https://gist.github.com/benjamingr/0237932cee84712951a2 

Cheers

**Comment by calvinmetcalf** [comment]
I have some very mixed feelings on this, on one hand it's an extremely useful feature on the other in's a non standard api so so this would no longer be a drop in replacement for native promises which can cause problems (see pouchdb/pouchdb#3839)

**Comment by benjamingr** [comment]
@calvinmetcalf it is a standard API in that everyone implements it, in fact native promises already do it in io.js and NodeJS accepted it but since the merger was declared they're just waiting for io.js to merge with node over the io.js codebase.

This is mostly useful in order to be compatible with native promises. https://github.com/nodejs/io.js/issues/256

Note that this mostly affects server-side usage.

**Comment by calvinmetcalf** [comment]
yeah it's browserify usage I'm thinking of that could be affected

**Comment by benjamingr** [comment]
Hmm how so? The code checks if `process` and `process.emit` are there and only emits the events then - it might be really nice to emit `window` events like bluebird does but that's not required of the spec.

You can see how I implemented this in Q here: https://github.com/kriskowal/q/commit/1c385073563ea76d0167a092118a5e1ce036b889

**Comment by calvinmetcalf** [comment]
if somebody does something like `var Promise = global.Promise || require('lie');` you would or would not have events depending on your browser

**Comment by benjamingr** [comment]
@calvinmetcalf if someone does `var Promise = global.Promise || require("lie");` you would not have events anyway since there is no `process` object.

These events already happen on the serverside in which case if a library is using `lie` instead of native promises they would not get errors. In fact you'd only get native errors if you do:

    var p = Promise.reject(new Error(...)); // fires an event if no `catch` is attached within a microtask flush
    var p = lie.reject(new Error(...)); // no process event, unlike native promises, Q, bluebird etc etc.

**Comment by calvinmetcalf** [comment]
let me look into how I can impliment it to work server side without increasing the client side code footprint unnecessarily

**Comment by benjamingr** [comment]
I was going to point out you can use a tool like envify and then use the fact minifiers strip dead code but it seems like you've figured something out already :) Thanks.

**Comment by calvinmetcalf** [comment]
Yeah the env seemed like a bit of a hack plus down stream packages could have used conflicting env stuff

**Comment by benjamingr** [comment]
Yes, the approach you took does sound better. Let me know if you need any help pushing this forward and thanks for doing this :)

**Comment by calvinmetcalf** [comment]
done in 2.9.0

**Comment by benjamingr** [comment]
Awesome, thanks a ton!
