### ISSUE TITLE
Webpack throws Warning

### ISSUE THREAD

**Issue by srcspider** [calvinmetcalf/lie#22]
I know `dist/lie.js` is not pre-built, but it still throw this warning due to the way its written...

```sh
WARNING in ./~/lie/dist/lie.js
Critical dependencies:
1:438-445 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/lie/dist/lie.js 1:438-445
```

For easier tracking of the error here's the warning as it appears when I `require('lie/lib')`, 

```sh
WARNING in ./~/lie/~/immediate/dist/immediate.js
Critical dependencies:
1:440-447 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/lie/~/immediate/dist/immediate.js 1:440-447
```

Incidentally I would prefer that the raw source (and by this I also mean `require`'ing the raw source on dependencies too) was actually the default when doing `require('lie')` since I believe the concatenated version may have issues with deduping but its not much of a issue otherwise, other then being hard to spot, since I personally alias all 3rd party libraries.

**Comment by srcspider** [comment]
`immediate` assuming the one I found is the correct one, seems to be at version `3.2` now. But `lie` requires `^3.0.0` (so `3.0.2` at the time of writing this)

**Comment by calvinmetcalf** [comment]
`dist/lie.js` *is* prebuild, the main entrense file (as specified in the package.json) is lib/index.js, I don't know how you are trying to load lie, but if you just install it with NPM and `require('lie');` it should work fine...

**Comment by srcspider** [comment]
I was doing `require('lie')`

From what I could tell the line in question just looks compiled due to the way its written.

**Comment by calvinmetcalf** [comment]
Are you using it from like bower or something?

Because unless you have Web pack set up strangely then version 2.8.2 of lie
requires ^3.0.0 which resolves to 3.2.0 (2.9.0 of lie which I put out 4
hours ago requires ~3.0.0 which resolves to 3.0.3)

The precompiled version,  might have used 3.0.2 of immediate, but that's
for use without build systems so shouldn't effect you.

Feel free to post your code or your package.json

**Comment by srcspider** [comment]
```sh
srcspider ~/Workspace
λ npm -v
2.10.0
srcspider ~/Workspace
λ node -v
v0.10.25
srcspider ~/Workspace
λ mkdir test
srcspider ~/Workspace
λ cd test
srcspider ~/Workspace/test
λ echo "{}" > package.json
srcspider ~/Workspace/test
λ npm i -S lie
npm WARN package.json @ No description
npm WARN package.json @ No repository field.
npm WARN package.json @ No README data
npm WARN package.json @ No license field.
lie@2.9.0 node_modules/lie
├── immediate@3.0.3
├── unreachable-branch-transform@0.2.3 (esmangle-evaluator@1.0.0, through2@0.6.5, recast@0.10.12)
└── inline-process-browser@1.0.0 (through2@0.6.5, falafel@1.1.0)
```
From `cat node_modules/lie`
```sh
{
  "name": "lie",
  "version": "2.9.0",
...
```
---
```js
require('lie')
```
```js
WARNING in ./~/lie/~/immediate/dist/immediate.js
Critical dependencies:
1:440-447 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/lie/~/immediate/dist/immediate.js 1:440-447
```
Seems the offending piece of code is `a(o,!0);`, the so called non-minified version of immediate is still more or less pre-processed with whitespace preserved (I think).

---

I've tinkered with the code of `lie` a bit. **To fix this error** you need to change all your uses of `require('immediate')` to `require('immediate/lib')` (see: `unwrap.js` and `handlers.js`)

**Comment by srcspider** [comment]
> Because unless you have Web pack set up strangely

With regard to this. I only have `appcache` and `dedupe` plugin in use. I've actually tried removing the `dedupe` plugin but doesn't seem to affect it. The rest of the webpack setup is pretty standard (I do use a few loaders, multiple entry points, etc but that shouldn't affect it).

`webpack` version is `1.9.10` (latest at this time)

**Comment by srcspider** [comment]
> ^3.0.0 which resolves to 3.2.0

I was a bit curios where the confusion here is. Seems npm on a clean install will look at `^3.0.0` and only search the last digit. But if a version of the package already exists (such as from a previous `npm i`) it will still match that (even though cleanly it would not install that). So I assume it only seems to work for you because you already had a package installed.

Essentially, `^3.0.0` will install `3.0.3` unless you already have `3.2.0` installed in which case it will not uninstall it, and not do anything. 

What you really want if you want any minior version and patch version is `^3.0` (I've tested with `^2.0` to make sure it doesn't change major version and the behavior works as intended, `2.7.2` is installed). 

*I'm a bit disappointed in this behavior of npm now.*

**Comment by calvinmetcalf** [comment]
https://github.com/calvinmetcalf/immediate/blob/946159793b95fc9e6d612572811369ad8a88fafd/package.json#L33,
unless webpack is grabbing the jam field for some reason I don't see why it
would be grabbing the dist version

**Comment by srcspider** [comment]
I just checked with a `console.log` and indeed `lib/index.js` is loaded (btw you why not just have index.js on the project root?). Sadly even though it's loaded the annoying warning is still there. Since you seem to have control of `immediate` can you make it so the generated clean dist version is not mangled? Or, apply the solution in `lie`. 

I've looked into what exactly generates this in webpack, and this this: 
https://github.com/webpack/webpack/blob/master/lib/CompatibilityPlugin.js

```
// support for browserify style require delegator: "require(o, !0)"
```

---

Here is reproduction code, the error is reported as part of statistics. If you do not print statistics you will not see the warning.

```sh
mkdir testcase
cd testcase
echo "{}" > package.json
npm i -D webpack
npm i -S lie
```

**main.js**
```js
var webpack = require('webpack');

webpack({

	entry: {
		test: './test.js'
	},

	resolveLoader: {
		root: './node_modules'
	},

	output: {
		// pathinfo: true,
		path: './build',
	},

}, function (err, stats) {

	if (err) {
		console.log(err);
	}

	console.log(stats.toString({
		chunks: false,
		colors: true
	}));
});
```

**test.js**
```js
require('lie');
```
To see the error just run,
```sh
node main.js
```

**Comment by calvinmetcalf** [comment]
it is the jam entry that is causing the issue, removing that fixes stuff

**Comment by calvinmetcalf** [comment]
will be publishing 3.0.4 which fixes that shortly
