### ISSUE TITLE
Exception Goblins

### ISSUE THREAD

**Issue by srcspider** [calvinmetcalf/lie#23]
I really like the library, but there's one major flaw/annoyance that constantly happens when trying to use it. And that is how it silently gobbles up errors, and lack of any ability to tell it to (at least temporarily) not do so. 

I understand this is probably due to the minimal nature or standard compliance but it would be really nice to have some global switch like `debug` we can turn on to force lie to spit out the errors. Doesn't need to be any fancy reporting either, something basic like `console.log(err.stack || err)` would do just fine; since in most cases it's just very simple mistakes that are just made complicated only by the fact they are not surfaced by `lie`.

This would be good not just for cases where the system unexpectedly fails but also for cases where the system continues to work even though there's been some serious failures; which are the worst.

Some of the annoying goblin cases:

```js
var Promise = require('lie');

errno = 0;

// throws error before resolve/reject are called
++errno;
var p = new Promise(function (resolve, reject) {
	throw new Error('Error #' + errno);
});

// resolves but throws error in resolver
++errno;
var p = new Promise(function (resolve, reject) {
	resolve(true);
}).then(function (d) {
	throw new Error('Error #' + errno);
});

// rejects with an Error object
// this may be personal bias but if it's specifically an Error object it
// never really makes sense to silently ignore it (other objects its fine)
++errno;
var p = new Promise(function (resolve, reject) {
	reject(new Error('Error #' + errno));
}).then(function (d) {
	// no reject handler
});

// does not resolve nor reject; there should be a debugTimeout
++errno;
var p = new Promise(function (resolve, reject) {
	// empty
}).then(function (d) {
	// do nothing
});

console.log(errno + ' errors should have happened');
```

A lot of the time the silent gobbling up just results in adding pointless `try` / `catch` for the purpose of just surfacing the error, only to remove them immediately after since there's no reason at all to do anything inside them other then overcome this annoyance in `lie`.

**Comment by calvinmetcalf** [comment]
In node you can add a listener on process for unhangledRejection which
should do what you want, not available in the browser though in order to
minimize size, so server side we got you cover, in the browser using
something like bluebird for debuging might work for you

**Comment by calvinmetcalf** [comment]
the other thing you can do is just make sure to always have a .catch at the end of your chain, closing this as I don't plan on adding any features not implemented by venders
