### ISSUE TITLE
WARN: Dropping unused variable UNHANDLED [dist/pouchdb.js:11612,4]

### ISSUE THREAD

**Issue by daleharvey** [calvinmetcalf/lie#26]
Started getting this when I PR'd to update lie

**Comment by calvinmetcalf** [comment]
yeah that whole code path is that uses that is statically deleted from the browser build, supose I should just declare the variable in there too

**Comment by calvinmetcalf** [comment]
can combine that with calvinmetcalf/immediate#21to shave a bit more off

**Comment by calvinmetcalf** [comment]
fixed in v3.0.1
