### ISSUE TITLE
Adding a .finally() method would be nice (src included)

### ISSUE THREAD

**Issue by tohagan** [calvinmetcalf/lie#28]
Although not included in ES6. The finally() method is very valuable.

Here's one implementation:

```
Promise.prototype.finally = function(callback) {
  var p = this.constructor;
  // We don’t invoke the callback in here,
  // because we want then() to handle its exceptions
  return this.then(
    // Callback fulfills: pass on predecessor settlement
    // Callback rejects: pass on rejection (=omit 2nd arg.)
    function(value) {
      p.resolve(callback()).then(function() { return value; });
    },
    function(reason) {
      p.resolve(callback()).then(function() { throw reason; });
    }
  );
}
```
- http://www.2ality.com/2014/10/es6-promises-api.html

**Comment by calvinmetcalf** [comment]
You can subclass this library (or native promises) to add this which is
probably what you want to do

**Comment by calvinmetcalf** [comment]
should work in node 4, firefox, chrome and via babel
```js
class FinallyPromise extends Promise {
  finally(callback) {
    var p = this.constructor;
    return this.then(resolve, reject);
    function resolve(value) {
      p.resolve(callback()).then(function() { return value; });
    };
    function reject(reason) {
      p.resolve(callback()).then(function() { throw reason; });
    }
  }
}
```

**Comment by tohagan** [comment]
Actually my need is for this in your lib so I can use it in the promises returned by [PouchDB](http://pouchdb.com) :) .  I don't (yet) need it in ES6. Sorry my reference to ES6 confused the conversation.  I was thinking that you may have only wanted to support strictly ES6 compatible lib.

**Comment by calvinmetcalf** [comment]
This library is meant to be a drop in replacement for native promises, if a native promise does not have a feature than this library will not support it, in PouchDB they use this library *only* when there is no native promises (aka es6 ones) available.  

If you need PouchDB promises to have a finally method you can do `FinallyPromise.resolve(pouchPromise)` which will add the finally method to the pouchPromise. You could also if you really wanted to do something like `global.Promise = FinallyPromise;` before loading pouchdb, I'd really recommend against that as it would change the promises for everyone.

**Comment by tohagan** [comment]
> This library is meant to be a drop in replacement for native promises,
I fully understand.  I wondered if that might be your intent.

> global.Promise = FinallyPromise;

I can't assume that I have ES6 Javascript - hence my approach was to use ES5 code to alter the Promise class so all Pouch responses pick it up with no wrapper required. I'm only adding a method - just for my apps - so I don't think this will affect anything else.

**Comment by calvinmetcalf** [comment]
[you can also use babel](https://babeljs.io/repl/#?experimental=false&evaluate=true&loose=true&spec=false&code=class%20FinallyPromise%20extends%20Promise%20{%0A%20%20finally%28callback%29%20{%0A%20%20%20%20var%20p%20%3D%20this.constructor%3B%0A%20%20%20%20return%20this.then%28resolve%2C%20reject%29%3B%0A%20%20%20%20function%20resolve%28value%29%20{%0A%20%20%20%20%20%20p.resolve%28callback%28%29%29.then%28function%28%29%20{%20return%20value%3B%20}%29%3B%0A%20%20%20%20}%3B%0A%20%20%20%20function%20reject%28reason%29%20{%0A%20%20%20%20%20%20p.resolve%28callback%28%29%29.then%28function%28%29%20{%20throw%20reason%3B%20}%29%3B%0A%20%20%20%20}%0A%20%20}%0A})

**Comment by Valve** [comment]
@calvinmetcalf Chrome has .finally in its Promise implementation. Also https://www.promisejs.org/api/ this has finally as part of its API (although not standard). May I please request you to revisit this decision?

**Comment by calvinmetcalf** [comment]
yeah it's [stage 3](https://github.com/tc39/proposals#stage-3) so I guess I can put it in

**Comment by tohagan** [comment]
Thanks
