### ISSUE TITLE
Inappropriate unhandled rejection error?

### ISSUE THREAD

**Issue by yaronyg** [calvinmetcalf/lie#30]
I wrote a silly library that lets us enqueue functions and run them serially. That is, each function won't be invoked until the function before it has completed. Each of the functions is itself asynchronous so we use promises both to let those enqueuing the functions track them as well as to manage executing them in order.

The problem I'm running into is that I'm getting an unhandled rejection error on a promise whose rejection is handled. The error is caused by the rejection of a promise that is successfully caught in a catch handler.

The rejected promise is defined [here](https://github.com/thaliproject/Thali_CordovaPlugin/blob/92c3c918949504fe515fe7ad53c1df8fd698a357/test/www/jxcore/bv_tests/testPromiseQueue.js#L57) and the successfully run catch handler is defined [here](https://github.com/thaliproject/Thali_CordovaPlugin/blob/92c3c918949504fe515fe7ad53c1df8fd698a357/test/www/jxcore/bv_tests/testPromiseQueue.js#L61). The test makes sure that the catch handler is properly called.

The code that this is executing is defined [here](https://github.com/thaliproject/Thali_CordovaPlugin/blob/92c3c918949504fe515fe7ad53c1df8fd698a357/thali/NextGeneration/promiseQueue.js#L65) and as you can see it uses two nested promises. The outer promise is returned to the enqueued caller and it is only this promise which will be rejected. Inside of it is a second promise that we use to manage the queue. Only it's resolve function (called globalResolve) will be called regardless of the outcome of the outer promise.

I know this format is a bit unorthodox but as I think the test shows we are handling the rejection so why are we still getting the unhandled rejection error?

Thanks! And I apologize in advance if this is something I'm screwing up on my side.

**Comment by yaronyg** [comment]
@mpodwysocki had the excellent idea of testing the code out in Node 4 with its built in Promise support. And it doesn't reproduce the bug. However I did have to cheat a tiny bit because Tape (or at least our flavor of it) doesn't seem to like Node 4.

So what I did was use the following test code at the bottom of the promiseQueue.js file:

```Javascript
process.on('unhandledRejection', function(error, self) {
  console.log("We have an unhandled rejection! " + error);
});

var promiseQueue = new PromiseQueue();
var firstPromise = promiseQueue.enqueue(function(resolve, reject) {
  console.log("I am in first promise");
  reject();
}).then(function() {
  console.log("I have resolved!");
}).catch(function() {
  console.log("We caught our problem!");
});
```

I then ran this through Node 4 using lie and got the output:

```
I am in first promise
We have an unhandled rejection! undefined
We caught our problem!
```

Where you can see I'm getting the unhandled rejection event.

But then I ran the same code using Node 4 but commented out lie so we would use the built in promise support. In that case the output I got was:

```
I am in first promise
We caught our problem!
```

So it seems that ES6 doesn't mind what we're up to. So this would seem like pretty firm evidence that there is a bug in lie.

**Comment by calvinmetcalf** [comment]
globalPromise is never handled, I think enqueue could be redefined as 

```js
PromiseQueue.prototype.enqueue = function (fn) {
  this.globalPromise = this.globalPromise.then(fn);
  return this.globalPromise;
};
```

**Comment by yaronyg** [comment]
globalPromise doesn't need a catch handler because it literally never fires a reject. It can only fire resolve.

And unfortunately the function provided doesn't work for us because regardless of the outcome of fn (e.g. resolve or reject) we need the next fn to be run.

That's the point, there are two different promises here. One is the promise for an individual fn. That is the one that can fail. The other is just a management mechanism we use to make sure that the second enqueued fn isn't called until the first enqueued fn has finished. The management mechanism doesn't care about the outcome of any particular fn. It just needs to know that a fn has completed (successfully or otherwise) so it can start the next fn (if any).

But I think the node 4 example above proves that there is a bug, at least if we define a bug as lie's behavior is not the same as ES6.

**Comment by calvinmetcalf** [comment]
so fyi unhandledRejection is not an ES6 thing it's a vague convention, more generally the event should fire with a reference to the unhandled promise, which one is it?

**Comment by yaronyg** [comment]
An excellent point, of course ES6 doesn't define unhandledRejection, that is a node.js thing. So I guess the better statement is "If Lie wants to replicate Node 4's unhandledRejection behavior then...." But honestly that isn't my focus. It's just making sure my code isn't horked.

I modified the test code as follows:

```Javascript
process.on('unhandledRejection', function(error, self) {
  console.log("We have an unhandled rejection! Error: " + error +
    ", Self: " + JSON.stringify(self));
});

var promiseQueue = new PromiseQueue();
var firstPromise = promiseQueue.enqueue(function(resolve, reject) {
  console.log("I am in first promise");
  reject(45);
}).then(function() {
  console.log("I have resolved!");
}).catch(function() {
  console.log("We caught our problem!");
});
```

The output is then

```
I am in first promise
We have an unhandled rejection! Error: 45, Self: {"state":["REJECTED"],"queue":[{"promise":{"state":["REJECTED"],"queue":[{"promise":{"state":["PENDING"],"queue":[],"handled":["UNHANDLED"]}}],"outcome":45,"handled":null}}],"outcome":45,"handled":["UNHANDLED"]}
We caught our problem!
```

So it looks like it is the first promise, e.g. [this one](https://github.com/thaliproject/Thali_CordovaPlugin/blob/92c3c918949504fe515fe7ad53c1df8fd698a357/thali/NextGeneration/promiseQueue.js#L65) since reject was never called on the second promise. But as you can see in the example above, we do have a catch on that promise.

Help!

**Comment by calvinmetcalf** [comment]
Hm I'll have to look into why that doesn't seem to count it as rejecting
tommorow

**Comment by calvinmetcalf** [comment]
ah figured it out, I was marking it as handled if there was a handler specifically on that particular promise, but it didn't take into account chaning

**Comment by yaronyg** [comment]
I just tested with 3.0.2 and it worked like a charm! Thank you!!!!!
