### ISSUE TITLE
Expecting a function in instanceof check, but got #<Object>

### ISSUE THREAD

**Issue by fiatjaf** [calvinmetcalf/lie#32]
Happens at

```javascript
exports.resolve = resolve;
function resolve(value) {
  if (value instanceof this) {
    return value;
  }
  return handlers.resolve(new this(INTERNAL), value);
}
```

I'm using Opera 36 (the newest, Chromium-based), it seems to expect `this` to be a function, but it is 

```
Object {
  all: all(iterable)
  default: Promise(resolver)
  race: race(iterable)
  reject: reject(reason)
  resolve: resolve(value)
  __proto__: Object
}
```

**Comment by calvinmetcalf** [comment]
ah, this assumes that resolve is a method of the Promise function, looks like you have some sort of other module loader that is changing it to default

**Comment by fiatjaf** [comment]
I don't understand. Could it be Babel doing wrong things? I don't remember exactly, but I think I tried to isolate the error and run it directly in the browser console, but I hadn't considered the module loader possibility, so I probably didn't check for it, but I will.

Also, I replaced `lie` with `bluebird` and it worked -- just after that I decided to open this issue.

**Comment by calvinmetcalf** [comment]
so this is supposed to run as `Promise.resolve`, that does not seem to be the case here so try importing it as `import Promise from 'lie'` assuming that isn't what your doing now.

**Comment by fiatjaf** [comment]
I was indeed importing it with `import Promise from 'lie'` and running it with `Promise.resolve().then(...)`, that was exactly when it crashed.

**Comment by calvinmetcalf** [comment]
hm then babel is doing something weird, though I should probably simplify
how the export is done
