### ISSUE TITLE
immediate still brings in browserify transforms

### ISSUE THREAD

**Issue by nolanlawson** [calvinmetcalf/lie#35]
So unfortunately 3.1.0 didn't reduce node_modules or install times by much:

![lie](https://cloud.githubusercontent.com/assets/283842/17198431/0209fd90-542a-11e6-86f8-a6861664eef3.png)

However, upgrading to latest `immediate` gives us a 2.3kB build size instead of 1.7kB.

A few possible solutions:

1. Fork the old version of `immediate` into a pretransformed version (e.g. `immediate-lie`), use that as the dep
2. Move the old version of `immediate` into this repo

What do you think?

**Comment by calvinmetcalf** [comment]
hey so I already use a special version of immediate for this, on the ~3.0.0 branch so I could fork off 3.0.5 and do the inline thing

**Comment by calvinmetcalf** [comment]
done with v3.0.6

**Comment by nolanlawson** [comment]
Sweeeet! This is the best version of lie yet. :)
