### ISSUE TITLE
Performance and memory vs bluebird

### ISSUE THREAD

**Issue by rafis** [calvinmetcalf/lie#36]
Why `lie`'s code much simplier than `bluebird`'s, but `bluebird` almost 3 times faster according to [benchmark](https://github.com/petkaantonov/bluebird/blob/master/docs/docs/benchmarks.md)? (and also has 4 times less memory consumption)

**Comment by calvinmetcalf** [comment]
You answered your own question, being fast and using less memory requires more code especially the deep black magic bluebird uses to be so fast. 

I in fact use bluebird myself in apps I write, but I use this library in libraries I write if they could be used in the browser. My rational is that if it's my app I'm ok with the size, but if it's I library I don't want to force others to have the large size in their app. Also bluebird does some stuff with the function constructor (or at least did) and that can cause issues with csp and kinters) linters so I wouldn't want that baked into a client side library

**Comment by rafis** [comment]
Thank you! I will now prefer `lie` for client-side and `bluebird` for server-side.
